/** Sensible US-centric short list — use for default form values. */
export const COMMON_TIMEZONES = [
    'America/New_York',
    'America/Chicago',
    'America/Denver',
    'America/Los_Angeles',
    'America/Phoenix',
    'America/Anchorage',
    'Pacific/Honolulu',
    'Europe/London',
    'Europe/Paris',
    'Asia/Tokyo',
    'UTC',
] as const;

const FALLBACK_TIMEZONES: readonly string[] = [
    'Africa/Abidjan',
    'Africa/Accra',
    'Africa/Cairo',
    'Africa/Casablanca',
    'Africa/Johannesburg',
    'Africa/Lagos',
    'Africa/Nairobi',
    'Africa/Tunis',
    'America/Anchorage',
    'America/Argentina/Buenos_Aires',
    'America/Bogota',
    'America/Cancun',
    'America/Caracas',
    'America/Chicago',
    'America/Denver',
    'America/Edmonton',
    'America/Halifax',
    'America/Havana',
    'America/Indiana/Indianapolis',
    'America/Jamaica',
    'America/Juneau',
    'America/Kentucky/Louisville',
    'America/Lima',
    'America/Los_Angeles',
    'America/Mexico_City',
    'America/New_York',
    'America/Panama',
    'America/Phoenix',
    'America/Puerto_Rico',
    'America/Regina',
    'America/Santiago',
    'America/Sao_Paulo',
    'America/St_Johns',
    'America/Toronto',
    'America/Vancouver',
    'America/Winnipeg',
    'Asia/Almaty',
    'Asia/Baghdad',
    'Asia/Bangkok',
    'Asia/Colombo',
    'Asia/Dhaka',
    'Asia/Dubai',
    'Asia/Hong_Kong',
    'Asia/Jakarta',
    'Asia/Jerusalem',
    'Asia/Karachi',
    'Asia/Kolkata',
    'Asia/Kuala_Lumpur',
    'Asia/Manila',
    'Asia/Riyadh',
    'Asia/Seoul',
    'Asia/Shanghai',
    'Asia/Singapore',
    'Asia/Taipei',
    'Asia/Tashkent',
    'Asia/Tehran',
    'Asia/Tokyo',
    'Atlantic/Reykjavik',
    'Australia/Adelaide',
    'Australia/Brisbane',
    'Australia/Darwin',
    'Australia/Melbourne',
    'Australia/Perth',
    'Australia/Sydney',
    'Europe/Amsterdam',
    'Europe/Athens',
    'Europe/Berlin',
    'Europe/Brussels',
    'Europe/Bucharest',
    'Europe/Budapest',
    'Europe/Copenhagen',
    'Europe/Dublin',
    'Europe/Helsinki',
    'Europe/Istanbul',
    'Europe/Lisbon',
    'Europe/London',
    'Europe/Madrid',
    'Europe/Moscow',
    'Europe/Oslo',
    'Europe/Paris',
    'Europe/Prague',
    'Europe/Rome',
    'Europe/Stockholm',
    'Europe/Vienna',
    'Europe/Warsaw',
    'Europe/Zurich',
    'Indian/Mauritius',
    'Pacific/Auckland',
    'Pacific/Fiji',
    'Pacific/Guam',
    'Pacific/Honolulu',
    'Pacific/Port_Moresby',
    'UTC',
];

/**
 * All IANA timezones supported by the browser, sorted alphabetically.
 * Falls back to FALLBACK_TIMEZONES on very old browsers.
 */
export const ALL_TIMEZONES: readonly string[] = (() => {
    try {
        // Intl.supportedValuesOf is ES2022 — not in older TS lib typings
        return (Intl as unknown as Record<string, (k: string) => string[]>)['supportedValuesOf']('timeZone');
    } catch {
        return FALLBACK_TIMEZONES;
    }
})();
